### ISSUE TITLE
v4.1.0-SNAPSHOT

### ISSUE THREAD

**Issue by Majekdor** [FarLandsMC/FarLands#11]
This issue will be used to track changes between `v4.0.0-SNAPSHOT` and `v4.1.0-SNAPSHOT`. Once v4.1.0 is ready these changes will be posted as patch notes to the community.

# Changes

### Fixed
- Vote link in `/vote` now works properly
- `/wild` will now run asynchronously to reduce server lag on use
- Legacy color codes will now work properly in chat/nicknames
- Staff playtime should now be correct
- Fixed hard coded height limit for things like teleportation and claims
- Media rank can now only fly in claims they own or have access trust in
- `/homes` now works when the player has no homes

### Added
- Added advancements in-game showing in discord #in-game
- Added ability to use [MiniMessage](https://docs.adventure.kyori.net/minimessage) codes where you use other codes, ex. signs, chat, nicknames
- `/home <home>` will now accept partial home names
- Added the ability to trust a player on all your claims with `/trust <player> all`
- Added `/stack hotbar`
- Added a new in-chat emote: `:tm:` → ™
- Chat formatting can now be used in `/msg`
- When a player returns from AFK, they will receive a "While you were gone..." message with various events that happened when they were afk
- Added `/homes` custom sorting, with `/homes sort [sort-type]`
- Added a message on `/movhome` that shows the previous location of the home.
- Added `/bright` command to media rank that gives night vision

### Removed
- Removed `/top playtime no-staff`, since staff playtime was reset with players
- Removed `/vanish` command from media rank
- Removed stacking of unstackable items within inventory (caused more bugs than worth it)

 ### Backend
- Switched from Gson to Moshi
- Switched from NMS NBT to adventure-nbt
- Converted TextUtils to adventure components and MiniMessage
- Converted storage of custom items from JSON to NBT
- Created new Pagination class for paginated components
- Converted GUIs to use components

**Comment by funnyboy-roks** [comment]
We're probably good to release these once #13 is merged and perhaps we add some more requirements.

**Comment by funnyboy-roks** [comment]
I think this can probably be closed now...
