### ISSUE TITLE
Convert struct classes to records

### ISSUE THREAD

**Issue by Majekdor** [FarLandsMC/FarLands#3]
Our "object" classes are stored [here](https://github.com/FarLandsMC/FarLands/tree/main/src/main/java/net/farlands/sanctuary/data/struct). Not all of them can be, but the ones that can should be converted to records.

**Comment by ReyhanPatria** [comment]
Hi! I'd like to contribute, I'm pretty new to contributing, I'd like to try this issue as it involves more code. But can I get a clarification on what records actually are? What do you want to be converted exactly?

**Comment by funnyboy-roks** [comment]
Hello! Thank you for your interest in contributing! Java records are a feature added in version 15, you can view more about them [here](https://openjdk.java.net/jeps/359).  The idea is to replace things that can be replaced in the package `net.farlands.sanctuary.data.struct`

**Comment by ReyhanPatria** [comment]
Would the converted classes be in the same package?

This seems simple enought I think, I'd like to work on this if you'd assign me to it. Thanks!

**Comment by funnyboy-roks** [comment]
Yes.  You'd be replacing the classes that are currently there if it can be replaced with a record.
Thank you again for your interest :D

**Comment by ReyhanPatria** [comment]
I'm having trouble downloading the RegionProtection depedency, it spits out this error
```
Authentication failed for https://maven.pkg.github.com/FarLandsMC/mavenpackages/com/kicas/rp/regionprotection/1.2.0-SNAPSHOT/regionprotection-1.2.0-SNAPSHOT.pom 401 Unauthorized
```

**Comment by funnyboy-roks** [comment]
Ah, you'll need to modify your `~/.m2/settings.xml` to have
```xml
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">
  <servers>
    <server>
      <id>github</id>
      <username>GITHUB USERNAME</username>
      <password>TOKEN</password>
    </server>
  </servers>
</settings>
```
Where `TOKEN` is a personal access token generated in GitHub

**Comment by ReyhanPatria** [comment]
Thanks, that fixed it!

**Comment by funnyboy-roks** [comment]
Thank you for your contribution! :D
